/// Generated by AssetsRefGenerator on 2020/08/21
class Res {
  static const String ic_add =
      "packages/flutter_number_picker/src/images/ic_add.svg";
  static const String ic_minus =
      "packages/flutter_number_picker/src/images/ic_minus.svg";
}
